<script setup>
import { Link, router } from "@inertiajs/vue3";
import { useConfirm } from "primevue/useconfirm";

defineProps({
    invitations: { type: Object, required: true },
});

const confirm = useConfirm();

const statusClass = (status) => ({
    unused: "bg-slate-50 text-slate-700 border-slate-200",
    submitted: "bg-amber-50 text-amber-700 border-amber-200",
    accepted: "bg-emerald-50 text-emerald-700 border-emerald-200",
    rejected: "bg-red-50 text-red-700 border-red-200",
    expired: "bg-zinc-100 text-zinc-600 border-zinc-200",
}[status] ?? "bg-slate-50 text-slate-700 border-slate-200");

const formatDate = (value) => {
    if (!value) return "-";

    return new Intl.DateTimeFormat("id-ID", {
        dateStyle: "medium",
        timeStyle: "short",
    }).format(new Date(value));
};

const urlWithTab = (url) => {
    const parsedUrl = new URL(url, window.location.origin);
    parsedUrl.searchParams.set("tab", "tokens");

    return `${parsedUrl.pathname}${parsedUrl.search}`;
};

const deleteInvite = (invite) => {
    if (invite.status !== "unused") return;

    confirm.require({
        message: `Hapus invitation token ${invite.token_fingerprint}? Link ini tidak akan bisa dipakai lagi.`,
        header: "Konfirmasi hapus invitation",
        icon: "pi pi-exclamation-triangle",
        acceptClass: "p-button-danger",
        accept: () => router.delete(`/admin/data-contributor-invitations/${invite.id}`, {
            preserveScroll: true,
        }),
    });
};
</script>

<template>
    <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div class="overflow-x-auto">
            <table class="w-full min-w-[980px] text-left text-sm">
                <thead class="border-b border-slate-200 bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500">
                    <tr>
                        <th class="px-5 py-3 font-bold">Token fingerprint</th>
                        <th class="px-5 py-3 font-bold">Status</th>
                        <th class="px-5 py-3 font-bold">Generated by</th>
                        <th class="px-5 py-3 font-bold">Created</th>
                        <th class="px-5 py-3 font-bold">Expires</th>
                        <th class="px-5 py-3 font-bold">Used</th>
                        <th class="px-5 py-3 font-bold">Registration request</th>
                        <th class="px-5 py-3 text-right font-bold">Action</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    <tr v-for="invite in invitations.data" :key="invite.id" class="hover:bg-slate-50/70">
                        <td class="px-5 py-4 font-mono text-xs text-slate-700">{{ invite.token_fingerprint }}</td>
                        <td class="px-5 py-4">
                            <span
                                class="inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-bold uppercase"
                                :class="statusClass(invite.status)"
                            >
                                {{ invite.status }}
                            </span>
                        </td>
                        <td class="px-5 py-4 font-semibold text-slate-800">{{ invite.created_by ?? "-" }}</td>
                        <td class="px-5 py-4 text-slate-600">{{ formatDate(invite.created_at) }}</td>
                        <td class="px-5 py-4 text-slate-600">{{ formatDate(invite.expires_at) }}</td>
                        <td class="px-5 py-4 text-slate-600">{{ formatDate(invite.used_at) }}</td>
                        <td class="px-5 py-4">
                            <div v-if="invite.request" class="max-w-xs">
                                <p class="font-semibold text-slate-900">{{ invite.request.display_name }}</p>
                                <p class="truncate font-mono text-xs text-slate-500">{{ invite.request.generated_email }}</p>
                            </div>
                            <span v-else class="text-xs font-medium text-slate-400">Belum disubmit</span>
                        </td>
                        <td class="px-5 py-4 text-right">
                            <button
                                v-if="invite.status === 'unused'"
                                type="button"
                                class="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-red-200 px-3 text-xs font-bold text-red-700 hover:bg-red-50"
                                @click="deleteInvite(invite)"
                            >
                                <i class="pi pi-trash text-[10px]" aria-hidden="true" />
                                Delete
                            </button>
                            <span v-else class="text-xs font-medium text-slate-400">Terkunci</span>
                        </td>
                    </tr>
                    <tr v-if="invitations.data.length === 0">
                        <td colspan="8" class="px-5 py-12 text-center text-slate-500">
                            <i class="pi pi-send mb-3 block text-3xl text-slate-300" aria-hidden="true" />
                            Belum ada invitation token.
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div
            v-if="invitations.links?.length > 3"
            class="flex flex-col gap-3 border-t border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"
        >
            <span class="text-xs font-medium text-slate-500">
                Menampilkan {{ invitations.from }} sampai {{ invitations.to }} dari {{ invitations.total }} invitation
            </span>
            <div class="flex flex-wrap gap-1">
                <template v-for="(link, index) in invitations.links" :key="index">
                    <Link
                        v-if="link.url"
                        :href="urlWithTab(link.url)"
                        v-html="link.label"
                        class="rounded-lg px-3 py-1.5 text-xs font-semibold"
                        :class="link.active ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100'"
                    />
                    <span
                        v-else
                        v-html="link.label"
                        class="rounded-lg px-3 py-1.5 text-xs font-semibold text-slate-300"
                    />
                </template>
            </div>
        </div>
    </div>
</template>
