<script setup>
import { Link } from "@inertiajs/vue3";

defineProps({
    requests: { type: Object, required: true },
});

const emit = defineEmits(["accept", "reject"]);

const statusClass = (status) => ({
    pending: "bg-amber-50 text-amber-700 border-amber-200",
    accepted: "bg-emerald-50 text-emerald-700 border-emerald-200",
    rejected: "bg-red-50 text-red-700 border-red-200",
}[status] ?? "bg-slate-50 text-slate-700 border-slate-200");

const formatDate = (value) => {
    if (!value) return "-";

    return new Intl.DateTimeFormat("id-ID", {
        dateStyle: "medium",
        timeStyle: "short",
    }).format(new Date(value));
};

const urlWithTab = (url) => {
    const parsedUrl = new URL(url, window.location.origin);
    parsedUrl.searchParams.set("tab", "requests");

    return `${parsedUrl.pathname}${parsedUrl.search}`;
};
</script>

<template>
    <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div class="overflow-x-auto">
            <table class="w-full min-w-[900px] text-left text-sm">
                <thead class="border-b border-slate-200 bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500">
                    <tr>
                        <th class="px-5 py-3 font-bold">Nama singkat</th>
                        <th class="px-5 py-3 font-bold">Email login</th>
                        <th class="px-5 py-3 font-bold">Nomor telepon</th>
                        <th class="px-5 py-3 font-bold">Status</th>
                        <th class="px-5 py-3 font-bold">Tanggal submit</th>
                        <th class="px-5 py-3 font-bold">Generated by</th>
                        <th class="px-5 py-3 text-right font-bold">Action</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    <tr v-for="request in requests.data" :key="request.id" class="hover:bg-slate-50/70">
                        <td class="px-5 py-4">
                            <div class="font-semibold text-slate-900">{{ request.display_name }}</div>
                            <div v-if="request.reject_reason" class="mt-1 max-w-xs truncate text-xs text-slate-500">
                                {{ request.reject_reason }}
                            </div>
                        </td>
                        <td class="px-5 py-4 font-mono text-xs text-slate-700">{{ request.generated_email }}</td>
                        <td class="px-5 py-4 text-slate-700">{{ request.phone }}</td>
                        <td class="px-5 py-4">
                            <span
                                class="inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-bold uppercase"
                                :class="statusClass(request.status)"
                            >
                                {{ request.status }}
                            </span>
                        </td>
                        <td class="px-5 py-4 text-slate-600">{{ formatDate(request.submitted_at) }}</td>
                        <td class="px-5 py-4 text-slate-600">{{ request.generated_by ?? "-" }}</td>
                        <td class="px-5 py-4 text-right">
                            <div v-if="request.status === 'pending'" class="inline-flex items-center gap-2">
                                <button
                                    type="button"
                                    class="inline-flex min-h-9 items-center gap-1.5 rounded-lg bg-emerald-600 px-3 text-xs font-bold text-white hover:bg-emerald-700"
                                    @click="emit('accept', request)"
                                >
                                    <i class="pi pi-check text-[10px]" aria-hidden="true" />
                                    Accept
                                </button>
                                <button
                                    type="button"
                                    class="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-red-200 px-3 text-xs font-bold text-red-700 hover:bg-red-50"
                                    @click="emit('reject', request)"
                                >
                                    <i class="pi pi-times text-[10px]" aria-hidden="true" />
                                    Reject
                                </button>
                            </div>
                            <span v-else class="text-xs font-medium text-slate-400">Sudah diproses</span>
                        </td>
                    </tr>
                    <tr v-if="requests.data.length === 0">
                        <td colspan="7" class="px-5 py-12 text-center text-slate-500">
                            <i class="pi pi-inbox mb-3 block text-3xl text-slate-300" aria-hidden="true" />
                            Belum ada registration request.
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div
            v-if="requests.links?.length > 3"
            class="flex flex-col gap-3 border-t border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"
        >
            <span class="text-xs font-medium text-slate-500">
                Menampilkan {{ requests.from }} sampai {{ requests.to }} dari {{ requests.total }} request
            </span>
            <div class="flex flex-wrap gap-1">
                <template v-for="(link, index) in requests.links" :key="index">
                    <Link
                        v-if="link.url"
                        :href="urlWithTab(link.url)"
                        v-html="link.label"
                        class="rounded-lg px-3 py-1.5 text-xs font-semibold"
                        :class="link.active ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100'"
                    />
                    <span
                        v-else
                        v-html="link.label"
                        class="rounded-lg px-3 py-1.5 text-xs font-semibold text-slate-300"
                    />
                </template>
            </div>
        </div>
    </div>
</template>
